
name: Test Action

# Controls when the workflow will run.
# Run this workflow every time a new commit is pushed to your repository
on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: tripal/setup-tripal-action@7.x-3.x-0.1
      with:
        php-version: 7.2
    - name: test_drush
      env:
        DRUSH: ${{ steps.foo.outputs.drush_path }}
      run: |
        echo "Output Drush Version: ${{ steps.foo.outputs.drush_version }}"
        $DRUSH --help
      shell: bash
